### ISSUE TITLE
Error on arm64

### ISSUE THREAD

**Issue by nicholaswilde** [nicholaswilde/docker-cryptpad#2]
I'm getting the following error on arm64
```
cryptpad    | buffer.js:606
cryptpad    |     slice: (buf, start, end) => buf.utf8Slice(start, end),
cryptpad    |                                     ^
cryptpad    |
cryptpad    | RangeError: Index out of range
cryptpad    |     at Object.slice (buffer.js:606:37)
cryptpad    |     at Buffer.toString (buffer.js:803:14)
cryptpad    |     at Object.readFileSync (fs.js:408:41)
cryptpad    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:22)
cryptpad    |     at Module.load (internal/modules/cjs/loader.js:985:32)
cryptpad    |     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
cryptpad    |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
cryptpad    |     at internal/main/run_main_module.js:17:47 {
cryptpad    |   code: 'ERR_OUT_OF_RANGE'
cryptpad    | }
cryptpad exited with code 1
```

**Comment by nicholaswilde** [comment]
Fixed arm64 with 56fd1be1aa25b9d65f55b3b1cf38c4a71e32dc97
